/**
 * Education Graph - India
 *
 * Phase 8.8: CareerOS India Opportunity Graph
 *
 * Defines the complete education pathway structure for India:
 * - School streams (PCM, PCB, Commerce, Arts)
 * - Entrance exams (JEE, NEET, CAT, CLAT, UPSC, etc.)
 * - College tiers and types
 * - Degree pathways
 *
 * @module education-graph
 * @version 1.0.0
 */

import {
  SchoolStreamNode,
  ExamNode,
  CollegeTypeNode,
  DegreeNode,
  OpportunityEdge,
  SchoolStream,
  ExamType,
  CollegeTier,
  DegreeType,
} from './opportunity-node-types';
import { GraphBuilder } from './graph-builder';

/**
 * Create all school stream nodes
 */
export function createSchoolStreamNodes(): SchoolStreamNode[] {
  const nodes: SchoolStreamNode[] = [
    {
      id: 'stream-pcm',
      type: 'SCHOOL_STREAM',
      name: 'PCM (Physics, Chemistry, Mathematics)',
      stream: 'PCM',
      description: 'Science stream with Physics, Chemistry, and Mathematics. Gateway to engineering, architecture, and technical careers.',
      subjects: ['Physics', 'Chemistry', 'Mathematics', 'English', 'Optional'],
      eligibleExams: ['exam-jee-main', 'exam-jee-advanced', 'exam-cuet', 'exam-nata'],
      eligibleDegrees: ['degree-btech', 'degree-be', 'degree-barch', 'degree-bsc', 'degree-bca'],
      typicalCareers: ['career-software', 'career-mechanical', 'career-civil', 'career-electrical', 'career-architecture'],
      optionalityScore: 0.75,
      tags: ['science', 'engineering', 'technical', 'mathematics'],
      metadata: {
        popularity: 'HIGH',
        competition: 'VERY_HIGH',
        typicalPercentage: 35,
      },
    },
    {
      id: 'stream-pcb',
      type: 'SCHOOL_STREAM',
      name: 'PCB (Physics, Chemistry, Biology)',
      stream: 'PCB',
      description: 'Science stream with Physics, Chemistry, and Biology. Gateway to medical and life sciences careers.',
      subjects: ['Physics', 'Chemistry', 'Biology', 'English', 'Optional'],
      eligibleExams: ['exam-neet', 'exam-aiims', 'exam-jipmer', 'exam-cuet'],
      eligibleDegrees: ['degree-mbbs', 'degree-bds', 'degree-bams', 'degree-bvsc', 'degree-bpharm', 'degree-bsc-bio'],
      typicalCareers: ['career-doctor', 'career-dentist', 'career-pharmacist', 'career-veterinary', 'career-research'],
      optionalityScore: 0.55,
      tags: ['science', 'medical', 'biology', 'healthcare'],
      metadata: {
        popularity: 'HIGH',
        competition: 'EXTREME',
        typicalPercentage: 25,
      },
    },
    {
      id: 'stream-pcmb',
      type: 'SCHOOL_STREAM',
      name: 'PCMB (Physics, Chemistry, Math, Biology)',
      stream: 'PCM',
      description: 'Science stream with all four core sciences. Maximum flexibility for both engineering and medical pathways.',
      subjects: ['Physics', 'Chemistry', 'Mathematics', 'Biology', 'English'],
      eligibleExams: ['exam-jee-main', 'exam-jee-advanced', 'exam-neet', 'exam-cuet'],
      eligibleDegrees: ['degree-btech', 'degree-mbbs', 'degree-be', 'degree-bds', 'degree-bsc', 'degree-bpharm'],
      typicalCareers: ['career-software', 'career-doctor', 'career-research', 'career-biotech'],
      optionalityScore: 0.9,
      tags: ['science', 'flexibility', 'elite', 'comprehensive'],
      metadata: {
        popularity: 'MODERATE',
        competition: 'EXTREME',
        typicalPercentage: 5,
      },
    },
    {
      id: 'stream-commerce',
      type: 'SCHOOL_STREAM',
      name: 'Commerce',
      stream: 'COMMERCE',
      description: 'Commerce stream with Accounting, Economics, and Business Studies. Gateway to finance, CA, and business careers.',
      subjects: ['Accountancy', 'Economics', 'Business Studies', 'Mathematics/Optional', 'English'],
      eligibleExams: ['exam-ca-foundation', 'exam-cs', 'exam-cma', 'exam-cuet', 'exam-clat', 'exam-cmat'],
      eligibleDegrees: ['degree-bcom', 'degree-bba', 'degree-bba-ib', 'degree-ba-econ', 'degree-llb'],
      typicalCareers: ['career-ca', 'career-cs', 'career-investment-banking', 'career-corporate-finance', 'career-lawyer'],
      optionalityScore: 0.7,
      tags: ['commerce', 'finance', 'business', 'accounting'],
      metadata: {
        popularity: 'HIGH',
        competition: 'HIGH',
        typicalPercentage: 25,
      },
    },
    {
      id: 'stream-arts',
      type: 'SCHOOL_STREAM',
      name: 'Arts/Humanities',
      stream: 'ARTS',
      description: 'Arts stream with History, Political Science, Psychology, Sociology. Gateway to civil services, design, law, and creative careers.',
      subjects: ['History', 'Political Science', 'Geography/Psychology/Sociology', 'Languages', 'Optional'],
      eligibleExams: ['exam-clat', 'exam-cuet', 'exam-upsc', 'exam-nid', 'exam-nift', 'exam-ceed'],
      eligibleDegrees: ['degree-ba', 'degree-bfa', 'degree-bdes', 'degree-llb', 'degree-ba-psych', 'degree-ba-journalism'],
      typicalCareers: ['career-civil-services', 'career-lawyer', 'career-designer', 'career-journalist', 'career-psychologist'],
      optionalityScore: 0.8,
      tags: ['arts', 'humanities', 'creative', 'civil-services', 'flexibility'],
      metadata: {
        popularity: 'MODERATE',
        competition: 'MODERATE',
        typicalPercentage: 10,
      },
    },
    {
      id: 'stream-vocational',
      type: 'SCHOOL_STREAM',
      name: 'Vocational',
      stream: 'VOCATIONAL',
      description: 'Vocational stream with practical skills training. Direct pathway to employment or specialized diplomas.',
      subjects: ['Trade Theory', 'Practical Skills', 'Related Subjects'],
      eligibleExams: ['exam-it', 'exam-polytechnic'],
      eligibleDegrees: ['degree-diploma', 'degree-it-certificate'],
      typicalCareers: ['career-technician', 'career-trade', 'career-supervisor'],
      optionalityScore: 0.4,
      tags: ['vocational', 'practical', 'employment-ready', 'skill-based'],
      metadata: {
        popularity: 'LOW',
        competition: 'LOW',
        typicalPercentage: 5,
      },
    },
  ];

  return nodes;
}

/**
 * Create all exam nodes
 */
export function createExamNodes(): ExamNode[] {
  const nodes: ExamNode[] = [
    // Engineering Exams
    {
      id: 'exam-jee-main',
      type: 'EXAM',
      name: 'JEE Main',
      examType: 'JEE_MAIN',
      description: 'Joint Entrance Examination Main for admission to NITs, IIITs, and other engineering colleges.',
      frequency: 'MULTIPLE',
      eligibilityCriteria: ['PCM in 12th', 'Age limit', 'Attempt limits'],
      syllabus: ['Physics', 'Chemistry', 'Mathematics'],
      difficulty: 'VERY_DIFFICULT',
      competitionLevel: 'EXTREME',
      successRate: 2,
      opensDoorsTo: ['college-tier-1-tech', 'college-tier-2-tech', 'college-tier-3-tech'],
      alternativeExams: ['exam-bitsat', 'exam-mhtcet', 'exam-wbjee'],
      tags: ['engineering', 'national', 'competitive'],
      metadata: {
        conductingBody: 'NTA',
        totalSeats: 50000,
      },
    },
    {
      id: 'exam-jee-advanced',
      type: 'EXAM',
      name: 'JEE Advanced',
      examType: 'JEE_ADVANCED',
      description: 'Joint Entrance Examination Advanced for admission to IITs. Only top JEE Main qualifiers can attempt.',
      frequency: 'ANNUAL',
      eligibilityCriteria: ['Top 2.5 lakh in JEE Main', 'Age limit', 'Attempt limits'],
      syllabus: ['Physics', 'Chemistry', 'Mathematics'],
      difficulty: 'VERY_DIFFICULT',
      competitionLevel: 'EXTREME',
      successRate: 5,
      opensDoorsTo: ['college-iit', 'college-iit', 'college-iit'],
      alternativeExams: [],
      tags: ['engineering', 'elite', 'iit'],
      metadata: {
        conductingBody: 'IITs',
        totalSeats: 16000,
      },
    },
    // Medical Exams
    {
      id: 'exam-neet',
      type: 'EXAM',
      name: 'NEET',
      examType: 'NEET',
      description: 'National Eligibility cum Entrance Test for admission to MBBS, BDS, AYUSH courses.',
      frequency: 'ANNUAL',
      eligibilityCriteria: ['PCB in 12th', 'Age limit', 'Indian citizen'],
      syllabus: ['Physics', 'Chemistry', 'Biology'],
      difficulty: 'VERY_DIFFICULT',
      competitionLevel: 'EXTREME',
      successRate: 3,
      opensDoorsTo: ['college-medical-govt', 'college-medical-private', 'degree-mbbs', 'degree-bds'],
      alternativeExams: ['exam-aiims', 'exam-jipmer'],
      tags: ['medical', 'national', 'competitive'],
      metadata: {
        conductingBody: 'NTA',
        totalSeats: 90000,
      },
    },
    // Management Exams
    {
      id: 'exam-cat',
      type: 'EXAM',
      name: 'CAT',
      examType: 'CAT',
      description: 'Common Admission Test for admission to IIMs and top B-schools for MBA.',
      frequency: 'ANNUAL',
      eligibilityCriteria: ['Bachelor degree', '50% aggregate'],
      syllabus: ['Verbal Ability', 'Data Interpretation', 'Logical Reasoning', 'Quantitative Aptitude'],
      difficulty: 'VERY_DIFFICULT',
      competitionLevel: 'EXTREME',
      successRate: 2,
      opensDoorsTo: ['college-iim', 'college-top-bschool', 'degree-mba'],
      alternativeExams: ['exam-xat', 'exam-nmat', 'exam-snap', 'exam-mat'],
      tags: ['management', 'mba', 'elite'],
      metadata: {
        conductingBody: 'IIMs',
        totalSeats: 5000,
      },
    },
    // Law Exams
    {
      id: 'exam-clat',
      type: 'EXAM',
      name: 'CLAT',
      examType: 'CLAT',
      description: 'Common Law Admission Test for admission to National Law Universities.',
      frequency: 'ANNUAL',
      eligibilityCriteria: ['12th pass', '45% aggregate'],
      syllabus: ['English', 'General Knowledge', 'Legal Reasoning', 'Logical Reasoning', 'Quantitative'],
      difficulty: 'DIFFICULT',
      competitionLevel: 'VERY_HIGH',
      successRate: 3,
      opensDoorsTo: ['college-nlu', 'degree-llb', 'degree-ba-llb'],
      alternativeExams: ['exam-ailet', 'exam-lsat'],
      tags: ['law', 'national', 'competitive'],
      metadata: {
        conductingBody: 'Consortium of NLUs',
        totalSeats: 2500,
      },
    },
    // Civil Services
    {
      id: 'exam-upsc',
      type: 'EXAM',
      name: 'UPSC CSE',
      examType: 'UPSC',
      description: 'Union Public Service Commission Civil Services Examination for IAS, IPS, IFS.',
      frequency: 'ANNUAL',
      eligibilityCriteria: ['Bachelor degree', 'Age 21-32', 'Indian citizen'],
      syllabus: ['General Studies', 'Optional Subject', 'Essay', 'Ethics', 'CSAT'],
      difficulty: 'VERY_DIFFICULT',
      competitionLevel: 'EXTREME',
      successRate: 0.2,
      opensDoorsTo: ['career-ias', 'career-ips', 'career-ifs', 'career-irs'],
      alternativeExams: ['exam-state-psc'],
      tags: ['civil-services', 'government', 'elite', 'ias'],
      metadata: {
        conductingBody: 'UPSC',
        totalSeats: 1000,
      },
    },
    // Chartered Accountancy
    {
      id: 'exam-ca-foundation',
      type: 'EXAM',
      name: 'CA Foundation',
      examType: 'CA_FOUNDATION',
      description: 'First level of Chartered Accountancy course. Can appear after 12th.',
      frequency: 'MULTIPLE',
      eligibilityCriteria: ['12th pass', 'Registered with ICAI'],
      syllabus: ['Accounting', 'Business Law', 'Economics', 'Mathematics/Stats'],
      difficulty: 'MODERATE',
      competitionLevel: 'MODERATE',
      successRate: 25,
      opensDoorsTo: ['exam-ca-intermediate'],
      alternativeExams: [],
      tags: ['ca', 'commerce', 'accounting'],
      metadata: {
        conductingBody: 'ICAI',
      },
    },
    {
      id: 'exam-ca-intermediate',
      type: 'EXAM',
      name: 'CA Intermediate',
      examType: 'CA_INTERMEDIATE',
      description: 'Second level of Chartered Accountancy after Foundation or direct entry.',
      frequency: 'MULTIPLE',
      eligibilityCriteria: ['CA Foundation pass', 'Or Graduation with required marks'],
      syllabus: ['Advanced Accounting', 'Corporate Law', 'Taxation', 'Costing', 'Auditing'],
      difficulty: 'VERY_DIFFICULT',
      competitionLevel: 'VERY_HIGH',
      successRate: 10,
      opensDoorsTo: ['exam-ca-final'],
      alternativeExams: [],
      tags: ['ca', 'commerce', 'professional'],
      metadata: {
        conductingBody: 'ICAI',
      },
    },
    {
      id: 'exam-ca-final',
      type: 'EXAM',
      name: 'CA Final',
      examType: 'CA_FINAL',
      description: 'Final level of Chartered Accountancy. Qualifies you as a Chartered Accountant.',
      frequency: 'MULTIPLE',
      eligibilityCriteria: ['CA Intermediate pass', 'Articleship completed'],
      syllabus: ['Financial Reporting', 'Strategic Financial Management', 'Advanced Auditing', 'Corporate Laws', 'Electives'],
      difficulty: 'VERY_DIFFICULT',
      competitionLevel: 'VERY_HIGH',
      successRate: 8,
      opensDoorsTo: ['career-ca', 'career-cfo', 'career-investment-banking'],
      alternativeExams: [],
      tags: ['ca', 'professional', 'final'],
      metadata: {
        conductingBody: 'ICAI',
      },
    },
    // GATE for PG
    {
      id: 'exam-gate',
      type: 'EXAM',
      name: 'GATE',
      examType: 'GATE',
      description: 'Graduate Aptitude Test in Engineering for PG admissions and PSUs.',
      frequency: 'ANNUAL',
      eligibilityCriteria: ['B.Tech/B.E. or final year'],
      syllabus: ['Engineering discipline specific'],
      difficulty: 'VERY_DIFFICULT',
      competitionLevel: 'VERY_HIGH',
      successRate: 15,
      opensDoorsTo: ['degree-mtech', 'degree-ms', 'career-psu'],
      alternativeExams: [],
      tags: ['engineering', 'pg', 'psu'],
      metadata: {
        conductingBody: 'IITs/IISc',
      },
    },
    // CUET
    {
      id: 'exam-cuet',
      type: 'EXAM',
      name: 'CUET',
      examType: 'CUET',
      description: 'Common University Entrance Test for admission to central universities.',
      frequency: 'ANNUAL',
      eligibilityCriteria: ['12th pass'],
      syllabus: ['Language', 'Domain subjects', 'General Test'],
      difficulty: 'MODERATE',
      competitionLevel: 'HIGH',
      successRate: 20,
      opensDoorsTo: ['college-central-university', 'degree-ba', 'degree-bsc', 'degree-bcom'],
      alternativeExams: ['exam-university-specific'],
      tags: ['ug', 'common', 'university'],
      metadata: {
        conductingBody: 'NTA',
      },
    },
    // Design Exams
    {
      id: 'exam-nid',
      type: 'EXAM',
      name: 'NID DAT',
      examType: 'NID',
      description: 'National Institute of Design Design Aptitude Test.',
      frequency: 'ANNUAL',
      eligibilityCriteria: ['12th pass', 'Age limit'],
      syllabus: ['Visualisation', 'Creativity', 'Problem Solving', 'General Knowledge'],
      difficulty: 'DIFFICULT',
      competitionLevel: 'VERY_HIGH',
      successRate: 5,
      opensDoorsTo: ['college-nid', 'degree-bdes'],
      alternativeExams: ['exam-ceed'],
      tags: ['design', 'creative', 'nid'],
      metadata: {
        conductingBody: 'NID',
      },
    },
    {
      id: 'exam-nift',
      type: 'EXAM',
      name: 'NIFT',
      examType: 'NIFT',
      description: 'National Institute of Fashion Technology entrance exam.',
      frequency: 'ANNUAL',
      eligibilityCriteria: ['12th pass'],
      syllabus: ['General Ability', 'Creative Ability', 'Situation Test'],
      difficulty: 'DIFFICULT',
      competitionLevel: 'VERY_HIGH',
      successRate: 5,
      opensDoorsTo: ['college-nift', 'degree-bdes-fashion'],
      alternativeExams: [],
      tags: ['fashion', 'design', 'nift'],
      metadata: {
        conductingBody: 'NIFT',
      },
    },
    // MBA Other
    {
      id: 'exam-xat',
      type: 'EXAM',
      name: 'XAT',
      examType: 'XAT',
      description: 'Xavier Aptitude Test for XLRI and XIMB.',
      frequency: 'ANNUAL',
      eligibilityCriteria: ['Bachelor degree'],
      syllabus: ['Verbal', 'Decision Making', 'Quant', 'General Knowledge'],
      difficulty: 'VERY_DIFFICULT',
      competitionLevel: 'VERY_HIGH',
      successRate: 5,
      opensDoorsTo: ['college-xlri', 'college-ximb'],
      alternativeExams: ['exam-cat'],
      tags: ['mba', 'xlri', 'management'],
      metadata: {
        conductingBody: 'XLRI',
      },
    },
  ];

  return nodes;
}

/**
 * Create all college type nodes
 */
export function createCollegeTypeNodes(): CollegeTypeNode[] {
  const nodes: CollegeTypeNode[] = [
    // Tier 1 Engineering
    {
      id: 'college-iit',
      type: 'COLLEGE_TYPE',
      name: 'IITs',
      tier: 'TIER_1',
      description: 'Indian Institutes of Technology - Premier engineering institutions in India.',
      reputationScore: 0.95,
      placementRate: 95,
      averagePackage: 25,
      researchOutput: 0.9,
      alumniNetworkStrength: 0.95,
      degreesOffered: ['degree-btech', 'degree-mtech', 'degree-phd'],
      entranceExamsAccepted: ['exam-jee-advanced'],
      locationTypes: ['METRO', 'TIER_2'],
      tags: ['tier-1', 'engineering', 'elite', 'government'],
      metadata: {
        count: 23,
        avgFees: 10,
      },
    },
    {
      id: 'college-nit',
      type: 'COLLEGE_TYPE',
      name: 'NITs',
      tier: 'TIER_1',
      description: 'National Institutes of Technology - Top government engineering colleges.',
      reputationScore: 0.85,
      placementRate: 85,
      averagePackage: 12,
      researchOutput: 0.7,
      alumniNetworkStrength: 0.8,
      degreesOffered: ['degree-btech', 'degree-mtech', 'degree-phd'],
      entranceExamsAccepted: ['exam-jee-main'],
      locationTypes: ['METRO', 'TIER_2'],
      tags: ['tier-1', 'engineering', 'government', 'national'],
      metadata: {
        count: 31,
        avgFees: 8,
      },
    },
    {
      id: 'college-iiit',
      type: 'COLLEGE_TYPE',
      name: 'IIITs',
      tier: 'TIER_1',
      description: 'Indian Institutes of Information Technology - Focus on IT and CS.',
      reputationScore: 0.82,
      placementRate: 88,
      averagePackage: 18,
      researchOutput: 0.75,
      alumniNetworkStrength: 0.75,
      degreesOffered: ['degree-btech-cs', 'degree-mtech'],
      entranceExamsAccepted: ['exam-jee-main'],
      locationTypes: ['METRO', 'TIER_2'],
      tags: ['tier-1', 'cs', 'it', 'engineering'],
      metadata: {
        count: 25,
        avgFees: 8,
      },
    },
    // Tier 1 Management
    {
      id: 'college-iim',
      type: 'COLLEGE_TYPE',
      name: 'IIMs',
      tier: 'TIER_1',
      description: 'Indian Institutes of Management - Premier management institutions.',
      reputationScore: 0.95,
      placementRate: 100,
      averagePackage: 28,
      researchOutput: 0.85,
      alumniNetworkStrength: 0.95,
      degreesOffered: ['degree-mba', 'degree-pgdm'],
      entranceExamsAccepted: ['exam-cat'],
      locationTypes: ['METRO', 'TIER_2'],
      tags: ['tier-1', 'management', 'mba', 'elite'],
      metadata: {
        count: 20,
        avgFees: 25,
      },
    },
    // Tier 1 Medical
    {
      id: 'college-aiims',
      type: 'COLLEGE_TYPE',
      name: 'AIIMS',
      tier: 'TIER_1',
      description: 'All India Institute of Medical Sciences - Premier medical colleges.',
      reputationScore: 0.98,
      placementRate: 100,
      averagePackage: 12,
      researchOutput: 0.95,
      alumniNetworkStrength: 0.95,
      degreesOffered: ['degree-mbbs', 'degree-md', 'degree-ms'],
      entranceExamsAccepted: ['exam-aiims', 'exam-neet'],
      locationTypes: ['METRO'],
      tags: ['tier-1', 'medical', 'elite', 'government'],
      metadata: {
        count: 15,
        avgFees: 2,
      },
    },
    // Tier 1 Law
    {
      id: 'college-nlu',
      type: 'COLLEGE_TYPE',
      name: 'NLUs',
      tier: 'TIER_1',
      description: 'National Law Universities - Premier law institutions.',
      reputationScore: 0.88,
      placementRate: 90,
      averagePackage: 15,
      researchOutput: 0.7,
      alumniNetworkStrength: 0.85,
      degreesOffered: ['degree-ba-llb', 'degree-llb', 'degree-llm'],
      entranceExamsAccepted: ['exam-clat'],
      locationTypes: ['METRO', 'TIER_2'],
      tags: ['tier-1', 'law', 'national'],
      metadata: {
        count: 22,
        avgFees: 15,
      },
    },
    // Tier 2 Engineering
    {
      id: 'college-tier-2-tech',
      type: 'COLLEGE_TYPE',
      name: 'Tier-2 Engineering Colleges',
      tier: 'TIER_2',
      description: 'Good private and state engineering colleges with decent placements.',
      reputationScore: 0.65,
      placementRate: 70,
      averagePackage: 6,
      researchOutput: 0.4,
      alumniNetworkStrength: 0.6,
      degreesOffered: ['degree-btech', 'degree-mtech'],
      entranceExamsAccepted: ['exam-jee-main', 'exam-state'],
      locationTypes: ['METRO', 'TIER_2', 'TIER_3'],
      tags: ['tier-2', 'engineering', 'private', 'state'],
      metadata: {
        avgFees: 12,
      },
    },
    // Tier 2 Management
    {
      id: 'college-tier-2-mba',
      type: 'COLLEGE_TYPE',
      name: 'Tier-2 B-Schools',
      tier: 'TIER_2',
      description: 'Good business schools with consistent placements.',
      reputationScore: 0.7,
      placementRate: 85,
      averagePackage: 10,
      researchOutput: 0.5,
      alumniNetworkStrength: 0.65,
      degreesOffered: ['degree-mba', 'degree-pgdm'],
      entranceExamsAccepted: ['exam-cat', 'exam-mat', 'exam-cmat'],
      locationTypes: ['METRO', 'TIER_2'],
      tags: ['tier-2', 'management', 'mba'],
      metadata: {
        avgFees: 12,
      },
    },
    // Tier 3
    {
      id: 'college-tier-3',
      type: 'COLLEGE_TYPE',
      name: 'Tier-3 Colleges',
      tier: 'TIER_3',
      description: 'Private and local colleges with basic infrastructure.',
      reputationScore: 0.4,
      placementRate: 40,
      averagePackage: 3,
      researchOutput: 0.2,
      alumniNetworkStrength: 0.3,
      degreesOffered: ['degree-btech', 'degree-bcom', 'degree-ba', 'degree-bsc'],
      entranceExamsAccepted: ['exam-state', 'exam-management-quota'],
      locationTypes: ['TIER_2', 'TIER_3', 'RURAL'],
      tags: ['tier-3', 'private', 'local'],
      metadata: {
        avgFees: 8,
      },
    },
    // International
    {
      id: 'college-international',
      type: 'COLLEGE_TYPE',
      name: 'International Universities',
      tier: 'INTERNATIONAL',
      description: 'Top universities abroad - US, UK, Canada, Australia, Singapore.',
      reputationScore: 0.95,
      placementRate: 90,
      averagePackage: 50,
      researchOutput: 0.9,
      alumniNetworkStrength: 0.9,
      degreesOffered: ['degree-btech', 'degree-bs', 'degree-ba', 'degree-ms', 'degree-mba'],
      entranceExamsAccepted: ['exam-sat', 'exam-gre', 'exam-gmat', 'exam-ielts', 'exam-toefl'],
      locationTypes: ['METRO'],
      tags: ['international', 'abroad', 'elite', 'expensive'],
      metadata: {
        avgFees: 200,
        currency: 'USD',
      },
    },
    // Central Universities
    {
      id: 'college-central-university',
      type: 'COLLEGE_TYPE',
      name: 'Central Universities',
      tier: 'TIER_2',
      description: 'Universities established by an Act of Parliament.',
      reputationScore: 0.7,
      placementRate: 60,
      averagePackage: 5,
      researchOutput: 0.6,
      alumniNetworkStrength: 0.6,
      degreesOffered: ['degree-ba', 'degree-bsc', 'degree-bcom', 'degree-ma', 'degree-msc'],
      entranceExamsAccepted: ['exam-cuet'],
      locationTypes: ['METRO', 'TIER_2'],
      tags: ['central', 'university', 'government', 'affordable'],
      metadata: {
        count: 50,
        avgFees: 0.5,
      },
    },
    // Design
    {
      id: 'college-nid',
      type: 'COLLEGE_TYPE',
      name: 'NID',
      tier: 'TIER_1',
      description: 'National Institute of Design - Premier design institute.',
      reputationScore: 0.9,
      placementRate: 95,
      averagePackage: 10,
      researchOutput: 0.8,
      alumniNetworkStrength: 0.85,
      degreesOffered: ['degree-bdes'],
      entranceExamsAccepted: ['exam-nid'],
      locationTypes: ['METRO'],
      tags: ['design', 'creative', 'elite'],
      metadata: {
        avgFees: 15,
      },
    },
  ];

  return nodes;
}

/**
 * Create all degree nodes
 */
export function createDegreeNodes(): DegreeNode[] {
  const nodes: DegreeNode[] = [
    // Engineering Degrees
    {
      id: 'degree-btech',
      type: 'DEGREE',
      name: 'B.Tech / B.E.',
      degreeType: 'BTECH',
      description: 'Bachelor of Technology / Bachelor of Engineering. 4-year professional engineering degree.',
      duration: 4,
      streamRequirement: ['PCM', 'PCMB'],
      entranceExams: ['exam-jee-main', 'exam-jee-advanced'],
      collegeTypes: ['college-iit', 'college-nit', 'college-iiit', 'college-tier-2-tech', 'college-tier-3'],
      skillsDeveloped: ['skill-programming', 'skill-problem-solving', 'skill-technical-analysis', 'skill-project-management'],
      careerOutcomes: ['career-software', 'career-core-engineering', 'career-analytics', 'career-consulting'],
      furtherEducation: ['degree-mtech', 'degree-ms', 'degree-mba'],
      optionalityScore: 0.8,
      lockInLevel: 'MEDIUM',
      tags: ['engineering', 'technical', 'undergraduate'],
      metadata: {
        avgFees: 8,
        totalIntake: 2000000,
      },
    },
    {
      id: 'degree-mtech',
      type: 'DEGREE',
      name: 'M.Tech',
      degreeType: 'MTECH',
      description: 'Master of Technology. 2-year postgraduate engineering degree.',
      duration: 2,
      streamRequirement: undefined,
      entranceExams: ['exam-gate'],
      collegeTypes: ['college-iit', 'college-nit', 'college-iiit'],
      skillsDeveloped: ['skill-advanced-technical', 'skill-research', 'skill-specialization'],
      careerOutcomes: ['career-core-engineering', 'career-research', 'career-academia'],
      furtherEducation: ['degree-phd'],
      optionalityScore: 0.6,
      lockInLevel: 'HIGH',
      tags: ['engineering', 'pg', 'technical'],
      metadata: {
        avgFees: 4,
      },
    },
    // Medical Degrees
    {
      id: 'degree-mbbs',
      type: 'DEGREE',
      name: 'MBBS',
      degreeType: 'MBBS',
      description: 'Bachelor of Medicine and Bachelor of Surgery. 5.5-year medical degree including internship.',
      duration: 5.5,
      streamRequirement: ['PCB', 'PCMB'],
      entranceExams: ['exam-neet'],
      collegeTypes: ['college-aiims', 'college-medical-govt', 'college-medical-private'],
      skillsDeveloped: ['skill-medical-knowledge', 'skill-patient-care', 'skill-diagnosis', 'skill-surgery'],
      careerOutcomes: ['career-doctor', 'career-surgeon', 'career-specialist'],
      furtherEducation: ['degree-md', 'degree-ms', 'degree-dm', 'degree-mch'],
      optionalityScore: 0.4,
      lockInLevel: 'HIGH',
      tags: ['medical', 'healthcare', 'doctor', 'undergraduate'],
      metadata: {
        avgFeesGovt: 0.5,
        avgFeesPrivate: 80,
        totalIntake: 90000,
      },
    },
    {
      id: 'degree-md',
      type: 'DEGREE',
      name: 'MD / MS',
      degreeType: 'MD',
      description: 'Doctor of Medicine / Master of Surgery. 3-year postgraduate medical degree.',
      duration: 3,
      streamRequirement: undefined,
      entranceExams: ['exam-neet-pg'],
      collegeTypes: ['college-aiims', 'college-medical-govt'],
      skillsDeveloped: ['skill-specialized-medicine', 'skill-advanced-surgery'],
      careerOutcomes: ['career-specialist', 'career-consultant'],
      furtherEducation: ['degree-dm', 'degree-mch'],
      optionalityScore: 0.3,
      lockInLevel: 'HIGH',
      tags: ['medical', 'pg', 'specialization'],
      metadata: {
        avgFees: 2,
      },
    },
    // Commerce Degrees
    {
      id: 'degree-bcom',
      type: 'DEGREE',
      name: 'B.Com',
      degreeType: 'BCOM',
      description: 'Bachelor of Commerce. 3-year undergraduate degree in commerce and accounting.',
      duration: 3,
      streamRequirement: ['COMMERCE', 'PCM', 'ARTS'],
      entranceExams: ['exam-cuet', 'exam-university'],
      collegeTypes: ['college-central-university', 'college-tier-2', 'college-tier-3'],
      skillsDeveloped: ['skill-accounting', 'skill-finance-basics', 'skill-business-knowledge'],
      careerOutcomes: ['career-accountant', 'career-banking', 'career-finance'],
      furtherEducation: ['degree-mcom', 'degree-mba', 'certification-ca'],
      optionalityScore: 0.7,
      lockInLevel: 'LOW',
      tags: ['commerce', 'accounting', 'business', 'undergraduate'],
      metadata: {
        avgFees: 1,
      },
    },
    {
      id: 'degree-mba',
      type: 'DEGREE',
      name: 'MBA',
      degreeType: 'MBA',
      description: 'Master of Business Administration. 2-year postgraduate management degree.',
      duration: 2,
      streamRequirement: undefined,
      entranceExams: ['exam-cat', 'exam-xat', 'exam-nmat'],
      collegeTypes: ['college-iim', 'college-tier-2-mba'],
      skillsDeveloped: ['skill-management', 'skill-leadership', 'skill-strategy', 'skill-analytics'],
      careerOutcomes: ['career-management', 'career-consulting', 'career-investment-banking', 'career-product-management'],
      furtherEducation: ['degree-phd-management'],
      optionalityScore: 0.85,
      lockInLevel: 'LOW',
      tags: ['management', 'business', 'pg', 'versatile'],
      metadata: {
        avgFeesTier1: 25,
        avgFeesTier2: 12,
      },
    },
    // Arts Degrees
    {
      id: 'degree-ba',
      type: 'DEGREE',
      name: 'B.A.',
      degreeType: 'BA',
      description: 'Bachelor of Arts. 3-year undergraduate degree in humanities.',
      duration: 3,
      streamRequirement: ['ARTS', 'COMMERCE', 'PCM', 'PCB'],
      entranceExams: ['exam-cuet'],
      collegeTypes: ['college-central-university', 'college-tier-2', 'college-tier-3'],
      skillsDeveloped: ['skill-communication', 'skill-critical-thinking', 'skill-research'],
      careerOutcomes: ['career-civil-services', 'career-content', 'career-teaching'],
      furtherEducation: ['degree-ma', 'degree-llb', 'degree-mba'],
      optionalityScore: 0.85,
      lockInLevel: 'LOW',
      tags: ['arts', 'humanities', 'flexible', 'undergraduate'],
      metadata: {
        avgFees: 0.5,
      },
    },
    {
      id: 'degree-llb',
      type: 'DEGREE',
      name: 'LLB',
      degreeType: 'LLB',
      description: 'Bachelor of Laws. 3-year or 5-year integrated law degree.',
      duration: 3,
      streamRequirement: ['ARTS', 'COMMERCE', 'PCM', 'PCB'],
      entranceExams: ['exam-clat', 'exam-ailet'],
      collegeTypes: ['college-nlu', 'college-tier-2', 'college-tier-3'],
      skillsDeveloped: ['skill-legal-reasoning', 'skill-argumentation', 'skill-research', 'skill-writing'],
      careerOutcomes: ['career-lawyer', 'career-corporate-legal', 'career-judiciary'],
      furtherEducation: ['degree-llm'],
      optionalityScore: 0.7,
      lockInLevel: 'MEDIUM',
      tags: ['law', 'legal', 'professional'],
      metadata: {
        avgFees: 10,
      },
    },
    // Design Degrees
    {
      id: 'degree-bdes',
      type: 'DEGREE',
      name: 'B.Des',
      degreeType: 'BDes',
      description: 'Bachelor of Design. 4-year undergraduate design degree.',
      duration: 4,
      streamRequirement: ['ARTS', 'PCM', 'PCB', 'COMMERCE'],
      entranceExams: ['exam-nid', 'exam-ceed', 'exam-uceed'],
      collegeTypes: ['college-nid', 'college-iit-design', 'college-tier-2'],
      skillsDeveloped: ['skill-design-thinking', 'skill-visualization', 'skill-prototyping', 'skill-creativity'],
      careerOutcomes: ['career-product-design', 'career-ux-design', 'career-fashion-design'],
      furtherEducation: ['degree-mdes'],
      optionalityScore: 0.75,
      lockInLevel: 'MEDIUM',
      tags: ['design', 'creative', 'undergraduate'],
      metadata: {
        avgFees: 15,
      },
    },
    // Computer Applications
    {
      id: 'degree-bca',
      type: 'DEGREE',
      name: 'BCA',
      degreeType: 'BCA',
      description: 'Bachelor of Computer Applications. 3-year undergraduate IT degree.',
      duration: 3,
      streamRequirement: ['PCM', 'COMMERCE', 'ARTS'],
      entranceExams: ['exam-university'],
      collegeTypes: ['college-tier-2', 'college-tier-3'],
      skillsDeveloped: ['skill-programming', 'skill-database', 'skill-web-development'],
      careerOutcomes: ['career-software', 'career-web-dev', 'career-testing'],
      furtherEducation: ['degree-mca', 'degree-mba'],
      optionalityScore: 0.65,
      lockInLevel: 'MEDIUM',
      tags: ['it', 'software', 'alternative-to-btech'],
      metadata: {
        avgFees: 3,
      },
    },
    {
      id: 'degree-mca',
      type: 'DEGREE',
      name: 'MCA',
      degreeType: 'MCA',
      description: 'Master of Computer Applications. 2-year postgraduate IT degree.',
      duration: 2,
      streamRequirement: undefined,
      entranceExams: ['exam-nimcet', 'exam-university'],
      collegeTypes: ['college-nit', 'college-tier-2'],
      skillsDeveloped: ['skill-advanced-programming', 'skill-system-design', 'skill-project-management'],
      careerOutcomes: ['career-software', 'career-systems-analyst'],
      furtherEducation: [],
      optionalityScore: 0.6,
      lockInLevel: 'HIGH',
      tags: ['it', 'pg', 'software'],
      metadata: {
        avgFees: 4,
      },
    },
    // Science Degrees
    {
      id: 'degree-bsc',
      type: 'DEGREE',
      name: 'B.Sc',
      degreeType: 'BSC',
      description: 'Bachelor of Science. 3-year undergraduate science degree.',
      duration: 3,
      streamRequirement: ['PCM', 'PCB', 'PCMB'],
      entranceExams: ['exam-cuet'],
      collegeTypes: ['college-central-university', 'college-tier-2', 'college-tier-3'],
      skillsDeveloped: ['skill-research', 'skill-analytical', 'skill-scientific-method'],
      careerOutcomes: ['career-research', 'career-teaching', 'career-analytics'],
      furtherEducation: ['degree-msc', 'degree-mtech', 'degree-ms'],
      optionalityScore: 0.7,
      lockInLevel: 'LOW',
      tags: ['science', 'research', 'flexible', 'undergraduate'],
      metadata: {
        avgFees: 1,
      },
    },
    // PhD
    {
      id: 'degree-phd',
      type: 'DEGREE',
      name: 'PhD',
      degreeType: 'PHD',
      description: 'Doctor of Philosophy. 4-6 year doctoral research degree.',
      duration: 5,
      streamRequirement: undefined,
      entranceExams: ['exam-net', 'exam-jrf', 'exam-university'],
      collegeTypes: ['college-iit', 'college-iisc', 'college-central-university'],
      skillsDeveloped: ['skill-research', 'skill-academic-writing', 'skill-expertise'],
      careerOutcomes: ['career-academia', 'career-research', 'career-rd'],
      furtherEducation: [],
      optionalityScore: 0.3,
      lockInLevel: 'HIGH',
      tags: ['research', 'doctorate', 'academia', 'highest-degree'],
      metadata: {
        avgFees: 0,
        stipend: 35000,
      },
    },
  ];

  return nodes;
}

/**
 * Create education pathway edges
 */
export function createEducationEdges(): OpportunityEdge[] {
  const edges: OpportunityEdge[] = [
    // School to Exam edges
    {
      id: 'edge-pcm-jee',
      source: 'stream-pcm',
      target: 'exam-jee-main',
      type: 'ENABLES',
      weight: 0.95,
      description: 'PCM students can appear for JEE',
      metadata: {},
    },
    {
      id: 'edge-pcb-neet',
      source: 'stream-pcb',
      target: 'exam-neet',
      type: 'ENABLES',
      weight: 0.95,
      description: 'PCB students can appear for NEET',
      metadata: {},
    },
    {
      id: 'edge-commerce-ca',
      source: 'stream-commerce',
      target: 'exam-ca-foundation',
      type: 'ENABLES',
      weight: 0.9,
      description: 'Commerce students can pursue CA',
      metadata: {},
    },
    {
      id: 'edge-arts-clat',
      source: 'stream-arts',
      target: 'exam-clat',
      type: 'ENABLES',
      weight: 0.85,
      description: 'Arts students can appear for CLAT',
      metadata: {},
    },

    // Exam to College edges
    {
      id: 'edge-jee-iit',
      source: 'exam-jee-advanced',
      target: 'college-iit',
      type: 'REQUIRES',
      weight: 1.0,
      description: 'JEE Advanced required for IITs',
      metadata: {},
    },
    {
      id: 'edge-neet-aiims',
      source: 'exam-neet',
      target: 'college-aiims',
      type: 'REQUIRES',
      weight: 0.95,
      description: 'NEET required for AIIMS',
      metadata: {},
    },
    {
      id: 'edge-cat-iim',
      source: 'exam-cat',
      target: 'college-iim',
      type: 'REQUIRES',
      weight: 0.95,
      description: 'CAT required for IIMs',
      metadata: {},
    },

    // College to Degree edges
    {
      id: 'edge-iit-btech',
      source: 'college-iit',
      target: 'degree-btech',
      type: 'LEADS_TO',
      weight: 0.95,
      description: 'IITs offer B.Tech',
      metadata: {},
    },
    {
      id: 'edge-aiims-mbbs',
      source: 'college-aiims',
      target: 'degree-mbbs',
      type: 'LEADS_TO',
      weight: 0.95,
      description: 'AIIMS offers MBBS',
      metadata: {},
    },

    // Degree to Career edges
    {
      id: 'edge-btech-software',
      source: 'degree-btech',
      target: 'career-software',
      type: 'LEADS_TO',
      weight: 0.7,
      description: 'B.Tech leads to software engineering',
      metadata: {},
    },
    {
      id: 'edge-mbbs-doctor',
      source: 'degree-mbbs',
      target: 'career-doctor',
      type: 'LEADS_TO',
      weight: 0.95,
      description: 'MBBS leads to medical practice',
      metadata: {},
    },

    // Further education edges
    {
      id: 'edge-btech-mtech',
      source: 'degree-btech',
      target: 'degree-mtech',
      type: 'LEADS_TO',
      weight: 0.3,
      description: 'B.Tech can lead to M.Tech',
      metadata: {},
    },
    {
      id: 'edge-mbbs-md',
      source: 'degree-mbbs',
      target: 'degree-md',
      type: 'LEADS_TO',
      weight: 0.8,
      description: 'MBBS leads to MD/MS specialization',
      metadata: {},
    },

    // Alternative paths
    {
      id: 'edge-btech-mba',
      source: 'degree-btech',
      target: 'degree-mba',
      type: 'PIVOT_PATH',
      weight: 0.4,
      description: 'Many engineers pivot to MBA',
      metadata: {},
    },
    {
      id: 'edge-ba-llb',
      source: 'degree-ba',
      target: 'degree-llb',
      type: 'LEADS_TO',
      weight: 0.3,
      description: 'BA can lead to LLB',
      metadata: {},
    },
  ];

  return edges;
}

/**
 * Build the complete education graph
 */
export function buildEducationGraph(): GraphBuilder {
  const builder = new GraphBuilder();

  // Add all nodes
  builder.addNodes(createSchoolStreamNodes());
  builder.addNodes(createExamNodes());
  builder.addNodes(createCollegeTypeNodes());
  builder.addNodes(createDegreeNodes());

  // Add career nodes (referenced by edges)
  builder.addNodes([
    {
      id: 'career-software',
      type: 'CAREER',
      name: 'Software Engineering',
      description: 'Career in software development and engineering',
      tags: ['tech', 'engineering', 'software'],
      metadata: { field: 'Technology' },
    },
    {
      id: 'career-doctor',
      type: 'CAREER',
      name: 'Medical Doctor',
      description: 'Career in medical practice',
      tags: ['medical', 'healthcare', 'doctor'],
      metadata: { field: 'Healthcare' },
    },
    {
      id: 'career-ca',
      type: 'CAREER',
      name: 'Chartered Accountant',
      description: 'Career in accounting and finance',
      tags: ['finance', 'accounting', 'ca'],
      metadata: { field: 'Finance' },
    },
    {
      id: 'career-lawyer',
      type: 'CAREER',
      name: 'Lawyer',
      description: 'Career in legal practice',
      tags: ['law', 'legal', 'advocate'],
      metadata: { field: 'Law' },
    },
    {
      id: 'career-management',
      type: 'CAREER',
      name: 'Management Professional',
      description: 'Career in business management',
      tags: ['management', 'business', 'mba'],
      metadata: { field: 'Business' },
    },
    {
      id: 'career-research',
      type: 'CAREER',
      name: 'Research Scientist',
      description: 'Career in academic and industrial research',
      tags: ['research', 'science', 'academia'],
      metadata: { field: 'Research' },
    },
    {
      id: 'career-biotech',
      type: 'CAREER',
      name: 'Biotechnology Professional',
      description: 'Career in biotechnology industry',
      tags: ['biotech', 'science', 'research'],
      metadata: { field: 'Biotechnology' },
    },
    {
      id: 'career-academia',
      type: 'CAREER',
      name: 'Academician',
      description: 'Career in teaching and academia',
      tags: ['teaching', 'academia', 'education'],
      metadata: { field: 'Education' },
    },
    {
      id: 'career-rd',
      type: 'CAREER',
      name: 'R&D Professional',
      description: 'Career in research and development',
      tags: ['rnd', 'research', 'development'],
      metadata: { field: 'R&D' },
    },
    {
      id: 'career-teaching',
      type: 'CAREER',
      name: 'Teacher',
      description: 'Career in school and college teaching',
      tags: ['teaching', 'education', 'school'],
      metadata: { field: 'Education' },
    },
    {
      id: 'career-analytics',
      type: 'CAREER',
      name: 'Data Analyst',
      description: 'Career in data analysis and business intelligence',
      tags: ['data', 'analytics', 'statistics'],
      metadata: { field: 'Analytics' },
    },
    {
      id: 'career-core-engineering',
      type: 'CAREER',
      name: 'Core Engineer',
      description: 'Career in core engineering disciplines',
      tags: ['engineering', 'mechanical', 'civil', 'electrical'],
      metadata: { field: 'Engineering' },
    },
    {
      id: 'career-consulting',
      type: 'CAREER',
      name: 'Management Consultant',
      description: 'Career in management consulting',
      tags: ['consulting', 'strategy', 'business'],
      metadata: { field: 'Consulting' },
    },
    {
      id: 'career-web-dev',
      type: 'CAREER',
      name: 'Web Developer',
      description: 'Career in web development',
      tags: ['web', 'development', 'frontend', 'backend'],
      metadata: { field: 'Web Development' },
    },
    {
      id: 'career-testing',
      type: 'CAREER',
      name: 'QA Engineer',
      description: 'Career in software testing and quality assurance',
      tags: ['testing', 'qa', 'quality'],
      metadata: { field: 'QA' },
    },
    {
      id: 'career-systems-analyst',
      type: 'CAREER',
      name: 'Systems Analyst',
      description: 'Career in systems analysis and design',
      tags: ['systems', 'analysis', 'design'],
      metadata: { field: 'IT' },
    },
    {
      id: 'career-mechanical',
      type: 'CAREER',
      name: 'Mechanical Engineer',
      description: 'Career in mechanical engineering',
      tags: ['mechanical', 'engineering', 'manufacturing'],
      metadata: { field: 'Engineering' },
    },
    {
      id: 'career-civil',
      type: 'CAREER',
      name: 'Civil Engineer',
      description: 'Career in civil engineering and construction',
      tags: ['civil', 'engineering', 'construction'],
      metadata: { field: 'Engineering' },
    },
    {
      id: 'career-electrical',
      type: 'CAREER',
      name: 'Electrical Engineer',
      description: 'Career in electrical engineering',
      tags: ['electrical', 'engineering', 'power'],
      metadata: { field: 'Engineering' },
    },
    {
      id: 'career-architecture',
      type: 'CAREER',
      name: 'Architect',
      description: 'Career in architecture',
      tags: ['architecture', 'design', 'construction'],
      metadata: { field: 'Architecture' },
    },
    {
      id: 'career-dentist',
      type: 'CAREER',
      name: 'Dentist',
      description: 'Career in dental practice',
      tags: ['dental', 'medical', 'healthcare'],
      metadata: { field: 'Dentistry' },
    },
    {
      id: 'career-pharmacist',
      type: 'CAREER',
      name: 'Pharmacist',
      description: 'Career in pharmacy',
      tags: ['pharmacy', 'medical', 'healthcare'],
      metadata: { field: 'Pharmacy' },
    },
    {
      id: 'career-veterinary',
      type: 'CAREER',
      name: 'Veterinarian',
      description: 'Career in veterinary medicine',
      tags: ['veterinary', 'animal', 'medical'],
      metadata: { field: 'Veterinary' },
    },
    {
      id: 'career-cs',
      type: 'CAREER',
      name: 'Company Secretary',
      description: 'Career as company secretary',
      tags: ['company-secretary', 'corporate', 'compliance'],
      metadata: { field: 'Corporate' },
    },
    {
      id: 'career-investment-banking',
      type: 'CAREER',
      name: 'Investment Banker',
      description: 'Career in investment banking',
      tags: ['finance', 'investment', 'banking'],
      metadata: { field: 'Finance' },
    },
    {
      id: 'career-corporate-finance',
      type: 'CAREER',
      name: 'Corporate Finance Professional',
      description: 'Career in corporate finance',
      tags: ['finance', 'corporate', 'business'],
      metadata: { field: 'Finance' },
    },
    {
      id: 'career-accountant',
      type: 'CAREER',
      name: 'Accountant',
      description: 'Career in accounting',
      tags: ['accounting', 'finance', 'business'],
      metadata: { field: 'Accounting' },
    },
    {
      id: 'career-corporate-law',
      type: 'CAREER',
      name: 'Corporate Lawyer',
      description: 'Career in corporate law',
      tags: ['law', 'corporate', 'legal'],
      metadata: { field: 'Law' },
    },
    {
      id: 'career-litigation',
      type: 'CAREER',
      name: 'Litigation Lawyer',
      description: 'Career in litigation',
      tags: ['law', 'litigation', 'court'],
      metadata: { field: 'Law' },
    },
    {
      id: 'career-judiciary',
      type: 'CAREER',
      name: 'Judicial Officer',
      description: 'Career in judiciary',
      tags: ['judiciary', 'law', 'court'],
      metadata: { field: 'Judiciary' },
    },
    {
      id: 'career-journalism',
      type: 'CAREER',
      name: 'Journalist',
      description: 'Career in journalism and media',
      tags: ['journalism', 'media', 'writing'],
      metadata: { field: 'Media' },
    },
    {
      id: 'career-civil-services',
      type: 'CAREER',
      name: 'Civil Servant',
      description: 'Career in civil services (IAS, IPS, IFS)',
      tags: ['civil-services', 'government', 'administration'],
      metadata: { field: 'Government' },
    },
  ]);

  // Add all edges
  builder.addEdges(createEducationEdges());

  return builder;
}

/**
 * Get education statistics
 */
export function getEducationStats(): {
  streamCount: number;
  examCount: number;
  collegeTypeCount: number;
  degreeCount: number;
} {
  return {
    streamCount: createSchoolStreamNodes().length,
    examCount: createExamNodes().length,
    collegeTypeCount: createCollegeTypeNodes().length,
    degreeCount: createDegreeNodes().length,
  };
}
