/**
 * CareerOS Intelligence Foundation Types
 * 
 * This file contains the core type definitions for the CareerOS Intelligence System.
 * These types form the contract between all intelligence engines and ensure type safety
 * across the entire recommendation pipeline.
 * 
 * Architecture Principle: Assessment answers NEVER directly generate recommendations.
 * Instead: Assessment Answers → StudentBelief → Future Engines
 */

// ============================================================================
// CORE PRIMITIVE TYPES
// ============================================================================

/**
 * Confidence score represents our certainty about a belief or inference.
 * Range: 0.0 (no confidence) to 1.0 (complete certainty)
 * 
 * Used throughout the system to weight decisions and recommendations.
 */
export type ConfidenceScore = number;

/**
 * Timestamp with millisecond precision for tracking belief evolution.
 */
export type BeliefTimestamp = number;

/**
 * Unique identifier for any entity in the intelligence system.
 */
export type EntityId = string;

/**
 * Evidence source indicates how a belief was derived.
 */
export enum EvidenceSource {
  DIRECT_ASSESSMENT = 'direct_assessment',     // Student explicitly stated this
  INFERRED_BEHAVIOR = 'inferred_behavior',     // Derived from interaction patterns
  PATTERN_MATCH = 'pattern_match',             // Matched against similar profiles
  EXTERNAL_DATA = 'external_data',             // Imported from external systems
  AI_INFERENCE = 'ai_inference',               // Generated by AI reasoning
  VALIDATED = 'validated',                     // Confirmed through follow-up
}

// ============================================================================
// STUDENT BELIEF SYSTEM
// ============================================================================

/**
 * A single piece of evidence supporting a belief.
 * Evidence is tracked to enable belief revision and explainability.
 */
export interface Evidence {
  /** Unique identifier for this evidence record */
  id: EntityId;
  
  /** Source of the evidence */
  source: EvidenceSource;
  
  /** Original raw data (e.g., assessment answer ID, interaction event) */
  rawData: string;
  
  /** When this evidence was recorded */
  timestamp: BeliefTimestamp;
  
  /** Confidence in this specific evidence (may differ from overall belief confidence) */
  confidence: ConfidenceScore;
  
  /** Human-readable explanation of how this evidence supports the belief */
  explanation: string;
}

/**
 * Motivation represents what drives a student's career decisions.
 * These are high-level intrinsic and extrinsic drivers.
 */
export interface Motivation {
  /** Unique identifier for this motivation type */
  id: EntityId;
  
  /** Human-readable name (e.g., "Creative Expression") */
  name: string;
  
  /** Detailed description of what this motivation means */
  description: string;
  
  /** How strongly this motivation applies to the student (0.0 - 1.0) */
  strength: ConfidenceScore;
  
  /** Evidence supporting this motivation assessment */
  evidence: Evidence[];
  
  /** Whether this motivation was explicitly stated or inferred */
  isExplicit: boolean;
}

/**
 * Strength represents a capability or talent the student possesses.
 * Strengths can be skills, personality traits, or cognitive abilities.
 */
export interface Strength {
  /** Unique identifier for this strength */
  id: EntityId;
  
  /** Human-readable name (e.g., "Analytical Thinking") */
  name: string;
  
  /** Category of strength (cognitive, social, technical, creative, etc.) */
  category: StrengthCategory;
  
  /** Detailed description */
  description: string;
  
  /** How developed this strength is in the student (0.0 - 1.0) */
  level: ConfidenceScore;
  
  /** Evidence supporting this strength assessment */
  evidence: Evidence[];
  
  /** Whether this strength was self-reported or observed */
  isSelfReported: boolean;
}

/**
 * Categories of strengths for organization and reasoning.
 */
export enum StrengthCategory {
  COGNITIVE = 'cognitive',           // Problem-solving, analytical thinking
  SOCIAL = 'social',                 // Communication, empathy, leadership
  TECHNICAL = 'technical',           // Programming, data analysis, tools
  CREATIVE = 'creative',             // Design, writing, artistic expression
  PRACTICAL = 'practical',           // Hands-on skills, execution
  ORGANIZATIONAL = 'organizational', // Planning, coordination, management
}

/**
 * Value represents what a student cares about in their career and life.
 * Values are fundamental to long-term satisfaction and regret minimization.
 */
export interface Value {
  /** Unique identifier for this value */
  id: EntityId;
  
  /** Human-readable name (e.g., "Work-Life Balance") */
  name: string;
  
  /** Detailed description of what this value means */
  description: string;
  
  /** How important this value is to the student (0.0 - 1.0) */
  importance: ConfidenceScore;
  
  /** Evidence supporting this value assessment */
  evidence: Evidence[];
  
  /** Whether compromising this value would cause significant dissatisfaction */
  isNonNegotiable: boolean;
}

/**
 * PersonalityTrait represents a stable characteristic of the student's personality.
 * Based on psychological frameworks but simplified for career reasoning.
 */
export interface PersonalityTrait {
  /** Unique identifier for this trait */
  id: EntityId;
  
  /** Trait name (e.g., "Openness", "Conscientiousness") */
  name: string;
  
  /** The dimension this trait represents */
  dimension: PersonalityDimension;
  
  /** Position on the dimension (-1.0 to 1.0, where 0 is neutral) */
  position: number;
  
  /** Confidence in this trait assessment */
  confidence: ConfidenceScore;
  
  /** Evidence supporting this trait assessment */
  evidence: Evidence[];
}

/**
 * Personality dimensions used in CareerOS.
 * These are simplified from Big Five but optimized for career reasoning.
 */
export enum PersonalityDimension {
  OPENNESS = 'openness',                    // Curiosity, creativity vs. practicality
  CONSCIENTIOUSNESS = 'conscientiousness',  // Organization, diligence vs. flexibility
  EXTRAVERSION = 'extraversion',            // Social engagement vs. solitude
  AGREEABLENESS = 'agreeableness',          // Cooperation vs. independence
  STABILITY = 'stability',                  // Emotional resilience vs. reactivity
  AUTONOMY = 'autonomy',                    // Independence vs. structure
}

/**
 * LifestylePreference represents how a student wants to live and work.
 * These are concrete preferences that affect day-to-day satisfaction.
 */
export interface LifestylePreference {
  /** Unique identifier for this preference */
  id: EntityId;
  
  /** Human-readable name (e.g., "Remote Work") */
  name: string;
  
  /** Category of lifestyle preference */
  category: LifestyleCategory;
  
  /** Detailed description */
  description: string;
  
  /** Preferred state or option */
  preference: string;
  
  /** How important this preference is (0.0 - 1.0) */
  importance: ConfidenceScore;
  
  /** Evidence supporting this preference */
  evidence: Evidence[];
}

/**
 * Categories of lifestyle preferences.
 */
export enum LifestyleCategory {
  WORK_ENVIRONMENT = 'work_environment',    // Office, remote, hybrid, field
  SCHEDULE = 'schedule',                    // Hours, flexibility, predictability
  LOCATION = 'location',                    // Geographic preferences
  TRAVEL = 'travel',                        // Travel requirements
  SOCIAL = 'social',                        // Team size, interaction frequency
  PACE = 'pace',                            // Work speed, pressure level
}

/**
 * Constraint represents a hard or soft limitation on career options.
 * Constraints can be financial, geographic, educational, or personal.
 */
export interface Constraint {
  /** Unique identifier for this constraint */
  id: EntityId;
  
  /** Human-readable name (e.g., "Location: Mumbai") */
  name: string;
  
  /** Type of constraint */
  type: ConstraintType;
  
  /** Detailed description */
  description: string;
  
  /** Whether this is a hard constraint (must be satisfied) or soft (preference) */
  isHardConstraint: boolean;
  
  /** How limiting this constraint is (0.0 = minor preference, 1.0 = absolute barrier) */
  severity: ConfidenceScore;
  
  /** Evidence supporting this constraint */
  evidence: Evidence[];
}

/**
 * Types of constraints that can limit career options.
 */
export enum ConstraintType {
  FINANCIAL = 'financial',              // Budget, salary requirements, debt
  GEOGRAPHIC = 'geographic',            // Location, relocation willingness
  EDUCATIONAL = 'educational',          // Degree requirements, certifications
  TEMPORAL = 'temporal',                // Time available, urgency
  PERSONAL = 'personal',                // Family, health, other commitments
  LEGAL = 'legal',                      // Visa, work authorization
}

/**
 * StudentBelief is the CENTRAL SOURCE OF TRUTH for the entire CareerOS system.
 * 
 * All assessment data flows into StudentBelief. All recommendation engines
 * read from StudentBelief. This creates a clean separation between data
 * collection and intelligence generation.
 * 
 * StudentBelief is versioned and immutable - updates create new versions
 * to enable belief evolution tracking and A/B testing of inference methods.
 */
export interface StudentBelief {
  /** Unique identifier for this belief snapshot */
  id: EntityId;
  
  /** Student identifier this belief belongs to */
  studentId: EntityId;
  
  /** Version number (increments with each update) */
  version: number;
  
  /** When this belief snapshot was created */
  timestamp: BeliefTimestamp;
  
  /** What drives this student's career decisions */
  motivations: Motivation[];
  
  /** What this student is good at */
  strengths: Strength[];
  
  /** What this student cares about */
  values: Value[];
  
  /** How this student thinks and behaves */
  personalityTraits: PersonalityTrait[];
  
  /** How this student wants to live */
  lifestylePreferences: LifestylePreference[];
  
  /** What limits this student's options */
  constraints: Constraint[];
  
  /** Overall confidence in the belief model (aggregate of component confidences) */
  overallConfidence: ConfidenceScore;
  
  /** Whether this belief has been validated through follow-up or external data */
  isValidated: boolean;
  
  /** Previous version of this belief (for tracking evolution) */
  previousVersionId?: EntityId;
  
  /** Metadata for debugging and analytics */
  metadata: {
    /** How many assessment questions contributed to this belief */
    assessmentQuestionCount: number;
    
    /** How many inference steps were applied */
    inferenceStepCount: number;
    
    /** Which engines contributed to this belief */
    contributingEngines: string[];
    
    /** Time spent in assessment (milliseconds) */
    assessmentDuration: number;
  };
}

// ============================================================================
// CAREER GRAPH TYPES
// ============================================================================

/**
 * CareerNode represents a single career option in the career graph.
 * Nodes are connected by edges that represent transition paths.
 */
export interface CareerNode {
  /** Unique identifier for this career */
  id: EntityId;
  
  /** Human-readable name (e.g., "Software Engineer") */
  name: string;
  
  /** Detailed description of what this career entails */
  description: string;
  
  /** Industry or sector (e.g., "Technology", "Healthcare") */
  industry: string;
  
  /** Category of work (e.g., "Technical", "Creative", "Service") */
  category: CareerCategory;
  
  /** Required strengths for this career */
  requiredStrengths: StrengthRequirement[];
  
  /** Values that align with this career */
  alignedValues: ValueAlignment[];
  
  /** Lifestyle characteristics of this career */
  lifestyleProfile: LifestyleProfile;
  
  /** Entry requirements (education, experience, certifications) */
  entryRequirements: EntryRequirement[];
  
  /** Career trajectory information */
  trajectory: CareerTrajectory;
  
  /** Market data for this career */
  marketData: CareerMarketData;
  
  /** Metadata for reasoning */
  metadata: {
    /** When this career data was last updated */
    lastUpdated: BeliefTimestamp;
    
    /** Data source (BLS, industry reports, etc.) */
    dataSource: string;
    
    /** Confidence in this career data */
    dataConfidence: ConfidenceScore;
  };
}

/**
 * Categories of careers for organization and filtering.
 */
export enum CareerCategory {
  TECHNICAL = 'technical',
  CREATIVE = 'creative',
  BUSINESS = 'business',
  SERVICE = 'service',
  SCIENTIFIC = 'scientific',
  TRADE = 'trade',
  HEALTHCARE = 'healthcare',
  EDUCATION = 'education',
  GOVERNMENT = 'government',
  ENTREPRENEURIAL = 'entrepreneurial',
}

/**
 * Strength requirement for a career.
 */
export interface StrengthRequirement {
  /** Strength ID required */
  strengthId: EntityId;
  
  /** Minimum level needed (0.0 - 1.0) */
  minimumLevel: ConfidenceScore;
  
  /** Whether this is a hard requirement or nice-to-have */
  isRequired: boolean;
  
  /** How important this strength is for success */
  importance: ConfidenceScore;
}

/**
 * Value alignment between a career and a value.
 */
export interface ValueAlignment {
  /** Value ID */
  valueId: EntityId;
  
  /** How well this career satisfies this value (-1.0 to 1.0) */
  alignment: number;
  
  /** Explanation of why this alignment exists */
  explanation: string;
}

/**
 * Lifestyle profile for a career.
 */
export interface LifestyleProfile {
  /** Typical work environment */
  workEnvironment: WorkEnvironmentType;
  
  /** Typical schedule flexibility */
  scheduleFlexibility: number;
  
  /** Typical travel requirements (0.0 - 1.0) */
  travelRequirement: ConfidenceScore;
  
  /** Typical team size */
  typicalTeamSize: { min: number; max: number };
  
  /** Remote work possibility (0.0 - 1.0) */
  remotePossibility: ConfidenceScore;
  
  /** Work pace (1 = slow/steady, 5 = fast/intense) */
  workPace: number;
}

/**
 * Types of work environments.
 */
export enum WorkEnvironmentType {
  OFFICE = 'office',
  REMOTE = 'remote',
  HYBRID = 'hybrid',
  FIELD = 'field',
  LAB = 'lab',
  VARIES = 'varies',
}

/**
 * Entry requirement for a career.
 */
export interface EntryRequirement {
  /** Type of requirement */
  type: EntryRequirementType;
  
  /** Description of the requirement */
  description: string;
  
  /** Whether this is a hard requirement */
  isRequired: boolean;
  
  /** Time typically needed to meet this requirement */
  typicalTimeToAcquire: string;
}

/**
 * Types of entry requirements.
 */
export enum EntryRequirementType {
  DEGREE = 'degree',
  CERTIFICATION = 'certification',
  EXPERIENCE = 'experience',
  PORTFOLIO = 'portfolio',
  SKILL = 'skill',
  NETWORK = 'network',
}

/**
 * Career trajectory information.
 */
export interface CareerTrajectory {
  /** Years to reach senior level */
  yearsToSenior: number;
  
  /** Years to reach leadership/management */
  yearsToLeadership: number;
  
  /** Whether this career has clear advancement paths */
  hasClearAdvancement: boolean;
  
  /** Alternative career paths from this node */
  pivotOptions: EntityId[];
  
  /** Specialization options within this career */
  specializationOptions: string[];
}

/**
 * Market data for a career.
 */
export interface CareerMarketData {
  /** Current demand level (1-5) */
  demandLevel: number;
  
  /** Projected growth rate */
  growthProjection: number;
  
  /** Salary range (local currency) */
  salaryRange: {
    entry: number;
    mid: number;
    senior: number;
  };
  
  /** Geographic availability */
  geographicAvailability: GeographicAvailability;
  
  /** Entry barrier level (1 = easy, 5 = very difficult) */
  entryBarrier: number;
}

/**
 * Geographic availability for a career.
 */
export interface GeographicAvailability {
  /** Whether this career is available globally */
  isGlobal: boolean;
  
  /** Regions where this career is in demand */
  inDemandRegions: string[];
  
  /** Whether remote work is common in this career */
  remoteCommon: boolean;
}

/**
 * CareerEdge represents a possible transition between two careers.
 * Edges form the career graph that enables pathfinding and regret analysis.
 */
export interface CareerEdge {
  /** Unique identifier for this edge */
  id: EntityId;
  
  /** Source career node */
  fromCareerId: EntityId;
  
  /** Target career node */
  toCareerId: EntityId;
  
  /** Type of transition this edge represents */
  transitionType: TransitionType;
  
  /** Difficulty of this transition (0.0 = easy, 1.0 = very difficult) */
  difficulty: ConfidenceScore;
  
  /** Typical time required for this transition */
  typicalTransitionTime: string;
  
  /** Skills that transfer between these careers */
  transferableSkills: EntityId[];
  
  /** Additional requirements for this transition */
  additionalRequirements: string[];
  
  /** How common this transition is */
  commonality: ConfidenceScore;
  
  /** Success rate for people attempting this transition */
  successRate?: ConfidenceScore;
}

/**
 * Types of career transitions.
 */
export enum TransitionType {
  ADVANCEMENT = 'advancement',       // Moving up in same field
  PIVOT = 'pivot',                   // Moving to related field
  TRANSITION = 'transition',         // Moving to different field
  SPECIALIZATION = 'specialization', // Deepening expertise
  GENERALIZATION = 'generalization', // Broadening scope
}

/**
 * CareerPath represents a sequence of career nodes and edges.
 * Paths are generated by the PathCascade engine and evaluated by other engines.
 */
export interface CareerPath {
  /** Unique identifier for this path */
  id: EntityId;
  
  /** Human-readable name for this path */
  name: string;
  
  /** Ordered sequence of career nodes in this path */
  nodes: CareerNode[];
  
  /** Edges connecting the nodes */
  edges: CareerEdge[];
  
  /** Total years for this path */
  totalYears: number;
  
  /** Student belief this path was generated for */
  studentBeliefId: EntityId;
  
  /** Scores from various evaluation engines */
  scores: PathScores;
  
  /** Whether this path has been validated by the student */
  isValidated: boolean;
  
  /** When this path was generated */
  generatedAt: BeliefTimestamp;
}

/**
 * Scores for a career path from various evaluation dimensions.
 */
export interface PathScores {
  /** How well this path matches student motivations (0.0 - 1.0) */
  motivationAlignment: ConfidenceScore;
  
  /** How well this path leverages student strengths (0.0 - 1.0) */
  strengthUtilization: ConfidenceScore;
  
  /** How well this path satisfies student values (0.0 - 1.0) */
  valueSatisfaction: ConfidenceScore;
  
  /** How feasible this path is given constraints (0.0 - 1.0) */
  feasibility: ConfidenceScore;
  
  /** Predicted regret score (lower is better) */
  predictedRegret: ConfidenceScore;
  
  /** Overall path quality score (composite) */
  overall: ConfidenceScore;
}

// ============================================================================
// DECISION COALITION TYPES
// ============================================================================

/**
 * DecisionCoalition V2 - India-First Stakeholder Model
 * 
 * Models career decisions as a coalition problem involving multiple stakeholders:
 * - Student (primary decision maker)
 * - Parents (significant influence, often financial sponsors)
 * - Extended family (cultural/social expectations)
 * 
 * This is the PRIMARY OUTPUT of the Decision Coalition Engine V2.
 */
export interface DecisionCoalition {
  /** Unique identifier for this coalition model */
  id: EntityId;
  
  /** Student this coalition belongs to */
  studentId: EntityId;
  
  /** Version number */
  version: number;
  
  /** When this coalition was modeled */
  timestamp: BeliefTimestamp;
  
  /** All stakeholders in the coalition */
  stakeholders: Stakeholder[];
  
  /** The 7 pressure factors */
  pressures: CoalitionPressures;
  
  /** Coalition dynamics summary */
  dynamics: CoalitionDynamics;
  
  /** Data for future parent-facing reports */
  parentReportData: ParentReportData;
  
  /** Family obligation calculations for future use - uses CoalitionFamilyObligation from DecisionCoalitionEngine */
  familyObligations: Array<{
    type: 'FINANCIAL_SUPPORT' | 'CAREGIVING' | 'STATUS_MAINTENANCE' | 'SIBLING_SUPPORT';
    description: string;
    estimatedMonthlyImpact?: number;
    timeline: 'IMMEDIATE' | 'SHORT_TERM' | 'LONG_TERM';
    flexibility: 'FIXED' | 'NEGOTIABLE' | 'FLEXIBLE';
  }>;
  
  /** Overall confidence in the coalition model */
  overallConfidence: ConfidenceScore;
  
  /** Number of assessment responses used */
  evidenceCount: number;
}

/**
 * Types of stakeholders in the career decision coalition.
 */
export type StakeholderType = 
  | 'STUDENT'
  | 'PARENT_PRIMARY'
  | 'PARENT_SECONDARY' 
  | 'EXTENDED_FAMILY'
  | 'SIBLING';

/**
 * A stakeholder in the career decision coalition.
 */
export interface Stakeholder {
  /** Unique identifier for this stakeholder instance */
  id: EntityId;
  
  /** Type of stakeholder */
  type: StakeholderType;
  
  /** Display name */
  name: string;
  
  /** Influence weight on decision (0.0 - 1.0) */
  weight: ConfidenceScore;
  
  /** Confidence in this weight estimate */
  confidence: ConfidenceScore;
  
  /** Evidence items supporting this weight */
  evidence: StakeholderEvidence[];
  
  /** Relationship to student */
  relationship?: string;
}

/**
 * Evidence for stakeholder weight determination.
 */
export interface StakeholderEvidence {
  /** Evidence identifier */
  id: string;
  
  /** Question that provided this evidence */
  questionId: string;
  
  /** Response value */
  response: string;
  
  /** How this evidence affects weight */
  impact: 'INCREASES_WEIGHT' | 'DECREASES_WEIGHT' | 'NEUTRAL';
  
  /** Human-readable explanation */
  explanation: string;
  
  /** Timestamp */
  timestamp: BeliefTimestamp;
}

/**
 * The 7 core coalition factors that model decision pressures.
 */
export interface CoalitionPressures {
  /** Student's relative decision-making power (0.0 - 1.0) */
  studentWeight: PressureFactor;
  
  /** Parent's relative decision-making power (0.0 - 1.0) */
  parentWeight: PressureFactor;
  
  /** Extended family's cultural/social influence (0.0 - 1.0) */
  familyInfluence: PressureFactor;
  
  /** Financial pressure on career choice (0.0 - 1.0) */
  financialPressure: PressureFactor;
  
  /** Urgency for immediate income (0.0 - 1.0) */
  incomeUrgency: PressureFactor;
  
  /** Family's collective risk tolerance (0.0 - 1.0) */
  riskTolerance: PressureFactor;
  
  /** Flexibility in career path choice (0.0 - 1.0) */
  careerFlexibility: PressureFactor;
}

/**
 * Individual pressure factor with value, confidence, and evidence.
 */
export interface PressureFactor {
  /** Estimated value (0.0 - 1.0) */
  value: ConfidenceScore;
  
  /** Confidence in this estimate */
  confidence: ConfidenceScore;
  
  /** Number of evidence items */
  evidenceCount: number;
  
  /** Evidence items */
  evidence: PressureEvidence[];
  
  /** Human-readable explanation */
  explanation: string;
}

/**
 * Evidence for pressure factor calculation.
 */
export interface PressureEvidence {
  /** Evidence identifier */
  id: string;
  
  /** Question that provided this evidence */
  questionId: string;
  
  /** Response value */
  response: string;
  
  /** Score contribution */
  contribution: number;
  
  /** Human-readable explanation */
  explanation: string;
  
  /** Timestamp */
  timestamp: BeliefTimestamp;
}

/**
 * Coalition dynamics summary.
 */
export interface CoalitionDynamics {
  /** Description of power balance */
  powerBalance: string;
  
  /** Whether student and parent weights are balanced */
  isBalanced: boolean;
  
  /** Potential conflict areas */
  conflictAreas: string[];
  
  /** Alignment between stakeholders (0.0 - 1.0) */
  stakeholderAlignment: ConfidenceScore;
  
  /** Primary decision maker */
  primaryDecisionMaker: StakeholderType;
}

/**
 * Data structured for parent-facing reports.
 */
export interface ParentReportData {
  /** Whether this data can be shown to parents */
  canShowToParents: boolean;
  
  /** Parent-friendly summary of coalition */
  parentSummary: string;
  
  /** Student's stated preferences (simplified) */
  studentPreferences: string[];
  
  /** Family constraints that affect options */
  familyConstraints: string[];
  
  /** Financial considerations */
  financialConsiderations: string[];
  
  /** Suggested conversation topics */
  conversationStarters: string[];
}

// Note: FamilyObligation is now defined in FamilyReality.ts
// Use the V3 domain type: import { FamilyObligation } from './FamilyReality'

/**
 * Legacy Voter - kept for backward compatibility with V1 coalition engine.
 * @deprecated Use Stakeholder instead
 */
export interface Voter {
  /** Unique identifier for this voter */
  id: EntityId;
  
  /** What this voter represents (e.g., "motivation_creativity") */
  name: string;
  
  /** Type of voter */
  type: VoterType;
  
  /** What this voter cares about */
  preference: Preference;
  
  /** How strongly this voter's vote counts (weight) */
  weight: ConfidenceScore;
  
  /** This voter's vote on a specific option */
  vote?: Vote;
}

/**
 * Types of voters in the coalition.
 */
export enum VoterType {
  MOTIVATION = 'motivation',
  STRENGTH = 'strength',
  VALUE = 'value',
  CONSTRAINT = 'constraint',
  LIFESTYLE = 'lifestyle',
  PERSONALITY = 'personality',
  MARKET = 'market',
  REGRET = 'regret',
}

/**
 * A preference held by a voter.
 */
export interface Preference {
  /** What is preferred */
  targetId: EntityId;
  
  /** Type of target */
  targetType: 'career' | 'path' | 'action';
  
  /** Strength of preference (0.0 - 1.0) */
  strength: ConfidenceScore;
  
  /** Why this preference exists */
  reasoning: string;
}

/**
 * A vote cast by a voter.
 */
export interface Vote {
  /** What is being voted on */
  optionId: EntityId;
  
  /** Score given (0.0 - 1.0) */
  score: ConfidenceScore;
  
  /** Confidence in this vote */
  confidence: ConfidenceScore;
  
  /** Explanation for this vote */
  reasoning: string;
}

/**
 * Methods for aggregating votes in a coalition.
 */
export enum AggregationMethod {
  WEIGHTED_AVERAGE = 'weighted_average',
  MAJORITY_RULE = 'majority_rule',
  BORDA_COUNT = 'borda_count',
  CONDORCET = 'condorcet',
}

// ============================================================================
// RECOMMENDATION TYPES
// ============================================================================

/**
 * CareerRecommendation is the final output of the recommendation engine.
 * It represents a suggested career path with full reasoning and confidence.
 */
export interface CareerRecommendation {
  /** Unique identifier for this recommendation */
  id: EntityId;
  
  /** Student this recommendation is for */
  studentId: EntityId;
  
  /** Student belief version used to generate this recommendation */
  studentBeliefId: EntityId;
  
  /** The recommended career path */
  path: CareerPath;
  
  /** Rank of this recommendation (1 = top) */
  rank: number;
  
  /** Overall confidence in this recommendation */
  confidence: ConfidenceScore;
  
  /** Detailed reasoning for this recommendation */
  reasoning: RecommendationReasoning;
  
  /** Potential concerns or caveats */
  concerns: RecommendationConcern[];
  
  /** Next steps to explore this recommendation */
  nextSteps: NextStep[];
  
  /** When this recommendation was generated */
  generatedAt: BeliefTimestamp;
  
  /** Which engines contributed to this recommendation */
  contributingEngines: string[];
}

/**
 * Detailed reasoning for a recommendation.
 */
export interface RecommendationReasoning {
  /** Why this path matches the student's motivations */
  motivationAlignment: string;
  
  /** Why this path leverages the student's strengths */
  strengthAlignment: string;
  
  /** Why this path satisfies the student's values */
  valueAlignment: string;
  
  /** Why this path is feasible given constraints */
  feasibilityReasoning: string;
  
  /** Why this path minimizes regret */
  regretReasoning: string;
  
  /** Summary of the recommendation */
  summary: string;
}

/**
 * A concern or caveat about a recommendation.
 */
export interface RecommendationConcern {
  /** What the concern is about */
  topic: string;
  
  /** Description of the concern */
  description: string;
  
  /** Severity of the concern (0.0 = minor, 1.0 = major) */
  severity: ConfidenceScore;
  
  /** How to address this concern */
  mitigation: string;
}

/**
 * A next step for exploring a recommendation.
 */
export interface NextStep {
  /** What to do */
  action: string;
  
  /** Why this step is recommended */
  reasoning: string;
  
  /** Priority of this step (1 = highest) */
  priority: number;
  
  /** Estimated time for this step */
  estimatedTime: string;
}

// ============================================================================
// REGRET ENGINE TYPES
// ============================================================================

/**
 * RegretPrediction represents a predicted future regret for a career decision.
 * The regret engine analyzes paths to predict which might cause regret.
 */
export interface RegretPrediction {
  /** Unique identifier for this prediction */
  id: EntityId;
  
  /** Career or path this prediction is about */
  targetId: EntityId;
  
  /** Type of target */
  targetType: 'career' | 'path';
  
  /** Type of regret predicted */
  regretType: RegretType;
  
  /** Likelihood of this regret (0.0 - 1.0) */
  likelihood: ConfidenceScore;
  
  /** Severity if this regret occurs (0.0 - 1.0) */
  severity: ConfidenceScore;
  
  /** When this regret might manifest (years from now) */
  timeHorizon: number;
  
  /** Why this regret is predicted */
  reasoning: string;
  
  /** Evidence supporting this prediction */
  evidence: Evidence[];
  
  /** How to mitigate this potential regret */
  mitigation: string;
}

/**
 * Types of career regrets.
 */
export enum RegretType {
  MISSED_OPPORTUNITY = 'missed_opportunity',     // Chose safe over dream
  WRONG_VALUES = 'wrong_values',                 // Compromised on important values
  UNREALIZED_POTENTIAL = 'unrealized_potential', // Didn't use strengths
  LIFESTYLE_MISMATCH = 'lifestyle_mismatch',   // Work-life balance issues
  FINANCIAL_REGRET = 'financial_regret',       // Salary/cost of living issues
  STAGNATION = 'stagnation',                   // No growth or learning
  ISOLATION = 'isolation',                     // Lack of connection/impact
}

// ============================================================================
// MENTOR TYPES
// ============================================================================

/**
 * MentorContext represents the context for a mentor interaction.
 * The mentor engine uses this to generate personalized guidance.
 */
export interface MentorContext {
  /** Student belief context */
  studentBelief: StudentBelief;
  
  /** Current recommendation being discussed */
  currentRecommendation?: CareerRecommendation;
  
  /** History of mentor interactions */
  interactionHistory: MentorInteraction[];
  
  /** Current emotional state of student (if known) */
  emotionalState?: EmotionalState;
  
  /** What the student is currently struggling with */
  currentConcern?: string;
}

/**
 * A single mentor interaction.
 */
export interface MentorInteraction {
  /** When this interaction occurred */
  timestamp: BeliefTimestamp;
  
  /** What the student asked or said */
  studentInput: string;
  
  /** How the mentor responded */
  mentorResponse: MentorResponse;
  
  /** Emotional state during this interaction */
  emotionalState: EmotionalState;
}

/**
 * A mentor response.
 */
export interface MentorResponse {
  /** The response text */
  text: string;
  
  /** Type of response */
  type: ResponseType;
  
  /** Suggested actions based on this response */
  suggestedActions: string[];
  
  /** Confidence in this response */
  confidence: ConfidenceScore;
}

/**
 * Types of mentor responses.
 */
export enum ResponseType {
  GUIDANCE = 'guidance',
  CLARIFICATION = 'clarification',
  ENCOURAGEMENT = 'encouragement',
  REALITY_CHECK = 'reality_check',
  EXPLORATION = 'exploration',
  ACTION_SUGGESTION = 'action_suggestion',
}

/**
 * Emotional states the student might be in.
 */
export enum EmotionalState {
  EXCITED = 'excited',
  HOPEFUL = 'hopeful',
  CURIOUS = 'curious',
  ANXIOUS = 'anxious',
  CONFUSED = 'confused',
  OVERWHELMED = 'overwhelmed',
  DOUBTFUL = 'doubtful',
  FRUSTRATED = 'frustrated',
  CONFIDENT = 'confident',
}

// ============================================================================
// UTILITY TYPES
// ============================================================================

/**
 * Result type for operations that can fail.
 */
export type Result<T, E = Error> = 
  | { success: true; data: T }
  | { success: false; error: E };

/**
 * Async result type.
 */
export type AsyncResult<T, E = Error> = Promise<Result<T, E>>;

/**
 * Filter criteria for career queries.
 */
export interface CareerFilter {
  /** Categories to include */
  categories?: CareerCategory[];
  
  /** Minimum salary requirement */
  minSalary?: number;
  
  /** Required work environment */
  workEnvironment?: WorkEnvironmentType[];
  
  /** Maximum acceptable entry barrier */
  maxEntryBarrier?: number;
  
  /** Geographic requirements */
  geographicRequirements?: string[];
  
  /** Whether remote work is required */
  requiresRemote?: boolean;
}

/**
 * Sort options for career queries.
 */
export enum CareerSortOption {
  MATCH_SCORE = 'match_score',
  SALARY = 'salary',
  GROWTH = 'growth',
  FEASIBILITY = 'feasibility',
  REGRET_RISK = 'regret_risk',
}

// ============================================================================
// REALITY DOMAINS - V3 EXPORTS
// ============================================================================

// Re-export FamilyReality types
export type {
  FamilyStructureType,
  FamilyStructure,
  HouseholdMember,
  ObligationType,
  FamilyObligation,
  ExpectationStrength,
  ParentalExpectation,
  SupportType,
  FamilySupport,
  CulturalConstraintType,
  CulturalConstraint,
  FamilyReality,
} from './FamilyReality';

// Re-export EconomicReality types
export type {
  IncomeBracket,
  FinancialSituation,
  FundingSourceType,
  EducationLoan,
  Scholarship,
  EducationFinancing,
  FundingSource,
  EconomicConstraintType,
  EconomicConstraint,
  ResourceAvailability,
  FinancialRiskTolerance,
  EconomicReality,
} from './EconomicReality';

// Re-export EducationalReality types
export type {
  AcademicStream,
  EducationBoard,
  InstitutionTier,
  AcademicBackground,
  AcademicPerformance,
  SubjectPerformance,
  AcademicAchievement,
  CompetitiveExamType,
  ExamStatus,
  CompetitiveExam,
  InstitutionStanding,
  LearningStyle,
  LearningEnvironment,
  LearningProfile,
  EducationalOpportunity,
  EducationalReality,
} from './EducationalReality';

// Re-export DecisionState types
export type {
  DecisionUrgency,
  DecisionDeadline,
  DecisionTimeline,
  PressureSource,
  DecisionPressureFactor,
  DecisionPressure,
  InformationCategory,
  InformationNeed,
  InformationStatus,
  ReadinessAspect,
  ReadinessComponent,
  DecisionReadiness,
  LifeSituation,
  DecisionEmotionalState,
  DecisionContext,
  DecisionState,
} from './DecisionState';

// Import V3 Reality Domain types for StudentBeliefV3 interface
import type { FamilyReality } from './FamilyReality';
import type { EconomicReality } from './EconomicReality';
import type { EducationalReality } from './EducationalReality';
import type { DecisionState as DecisionStateType } from './DecisionState';

// ============================================================================
// STUDENT BELIEF V3
// ============================================================================

/**
 * StudentBelief V3 - Enhanced with Reality Domains and Decision State
 *
 * V3 adds four new intelligence domains to the StudentBelief model:
 *   1. FamilyReality - Family context, obligations, expectations
 *   2. EconomicReality - Financial situation, constraints, resources
 *   3. EducationalReality - Academic background, achievements, opportunities
 *   4. DecisionState - Timeline, pressure, readiness, context
 *
 * These domains enable more nuanced career recommendations that account
 * for the student's complete reality - not just their psychology.
 */
export interface StudentBeliefV3 {
  /** Unique identifier for this belief snapshot */
  id: EntityId;

  /** Student identifier this belief belongs to */
  studentId: EntityId;

  /** Version number (V3 = 3) */
  version: 3;

  /** When this belief snapshot was created */
  timestamp: BeliefTimestamp;

  // ==========================================================================
  // PSYCHOLOGY LAYER (from V2)
  // ==========================================================================

  /** What drives this student's career decisions */
  motivations: Motivation[];

  /** What this student is good at */
  strengths: Strength[];

  /** What this student cares about */
  values: Value[];

  /** How this student thinks and behaves */
  personalityTraits: PersonalityTrait[];

  /** How this student wants to live */
  lifestylePreferences: LifestylePreference[];

  /** What limits this student's options */
  constraints: Constraint[];

  // ==========================================================================
  // REALITY LAYER (NEW in V3)
  // ==========================================================================

  /** Family reality - obligations, expectations, support, cultural factors */
  familyReality: FamilyReality;

  /** Economic reality - financial situation, constraints, resources */
  economicReality: EconomicReality;

  /** Educational reality - academic background, achievements, opportunities */
  educationalReality: EducationalReality;

  // ==========================================================================
  // DECISION CONTEXT LAYER (NEW in V3)
  // ==========================================================================

  /** Decision state - timeline, pressure, readiness, context */
  decisionState: DecisionStateType;

  // ==========================================================================
  // METADATA
  // ==========================================================================

  /** Overall confidence in the belief model */
  overallConfidence: ConfidenceScore;

  /** Whether this belief has been validated through follow-up or external data */
  isValidated: boolean;

  /** Previous version of this belief (for tracking evolution) */
  previousVersionId?: EntityId;

  /** Metadata for debugging and analytics */
  metadata: {
    /** How many assessment questions contributed to this belief */
    assessmentQuestionCount: number;

    /** How many inference steps were applied */
    inferenceStepCount: number;

    /** Which engines contributed to this belief */
    contributingEngines: string[];

    /** Time spent in assessment (milliseconds) */
    assessmentDuration: number;

    /** Migration info if upgraded from V2 */
    migratedFromV2?: {
      originalVersion: number;
      migratedAt: BeliefTimestamp;
      migrationReason: string;
    };
  };
}
